name: fake_news_detector
description: A Flutter app to detect fake news using Gemini AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0
  url_launcher: ^6.2.5
  flutter_staggered_grid_view: ^0.7.0
  dotted_border: ^2.1.0
  intl: ^0.19.0
  http_parser: ^4.1.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
